# Generated by Django 3.2 on 2023-07-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apoderado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltipomantenimiento',
            name='tipo_mantenimiento_descripcion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
